{
 "title": "Sliding Sync",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "window_size", "label": "Window size", "query": "30s,1m,2m,5m,10m,15m,30m,1h,2h" },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Sliding Sync API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "# active sliding sync connections",
   "type": "timeseries",
   "description": "Actively syncing clients i.e the connection hasn't expired yet. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "conns" } },
   "targets": [
    {
     "expr": "sum(sliding_sync_api_num_active_conns)",
     "legendFormat": "Active Connections"
    },
    {
     "expr": "increase(sliding_sync_api_expiry_conn_buffer_full[5m])",
     "legendFormat": "Expired Connections (full buffer)"
    },
    {
     "expr": "increase(sliding_sync_api_expiry_conn_timed_out[5m])",
     "legendFormat": "Expired Connections (timed out)"
    }
   ]
  },
  {
   "title": "EnsurePolling calls outstanding",
   "type": "timeseries",
   "description": "The number of devices blocked on an initial v2 sync. This number should never remain >0 for more than 15 minutes, unless there is a flood of new users to the system.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "conns" } },
   "targets": [
    {
     "expr": "sliding_sync_api_num_devices_pending_ensure_polling",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API processing time quantiles",
   "type": "timeseries",
   "description": "Excludes time waiting for live updates. Excludes initial requests.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(sliding_sync_api_process_duration_secs_bucket{initial=\"0\"}[$window_size])))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(sliding_sync_api_process_duration_secs_bucket{initial=\"0\"}[$window_size])))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(sliding_sync_api_process_duration_secs_bucket{initial=\"0\"}[$window_size])))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(sliding_sync_api_process_duration_secs_bucket{initial=\"0\"}[$window_size])))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(sliding_sync_api_process_duration_secs_bucket{initial=\"0\"}[$window_size])))",
     "legendFormat": "25%"
    },
    {
     "expr": "sum(rate(sliding_sync_api_process_duration_secs_count{initial=\"0\"}[$window_size]))",
     "legendFormat": "Request rate"
    }
   ]
  },
  {
   "title": "Request setup times",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(sliding_sync_api_setup_duration_secs_bucket{}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Slow requests",
   "type": "timeseries",
   "description": "Requests take more that 50s. This is our best proxy for \"how many people's requests are wedged\". Should be a flat 0.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(sliding_sync_api_slow_requests[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time taken to process initial sliding sync requests",
   "type": "heatmap",
   "description": "If this goes high, it may indicate poor DB performance when querying.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(sliding_sync_api_process_duration_secs_bucket{initial=\"1\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Time taken to process changes (ranges/filter/sorting/etc) in sliding sync requests",
   "type": "heatmap",
   "description": "Excludes live streaming blocks. If this goes high, it may indicate poor DB performance when querying.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(sliding_sync_api_process_duration_secs_bucket{initial=\"0\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "V2 Poller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "# v2 pollers",
   "type": "timeseries",
   "description": "Number of /sync connections to upstream homeserver. Generally always goes up, unless users log out and invalidate the access_token being used.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "pollers" } },
   "targets": [
    {
     "expr": "sliding_sync_poller_num_pollers{}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Time taken to process sync v2 responses",
   "type": "heatmap",
   "description": "The higher this is, the bigger the latency from sending events -> receiving events. Excludes initial /sync requests",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum(increase(sliding_sync_poller_process_duration_secs_bucket{initial=\"0\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Ratio of pollers waiting for v2 response",
   "type": "timeseries",
   "description": "If this drops too low, this means pollers are blocked on something (DB conns, executor, etc)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sliding_sync_poller_num_outstanding_sync_v2_reqs{}/sliding_sync_poller_num_pollers{}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rate of poll loop iterations",
   "type": "timeseries",
   "description": "If this number drops to 0, this indicates something is blocking all pollers from doing work. This number will scale with the number of pollers on the process.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "rate(sliding_sync_poller_total_num_polls{}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Timeline size of unlimited pollers",
   "type": "heatmap",
   "description": "NB: Proxy requests a timeline limit of 50.\n\nTODO: make it clear how many syncs were limited",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum(rate(sliding_sync_poller_timeline_size_bucket{limited=\"unlimited\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{limited}}"
    }
   ]
  },
  {
   "title": "Payload Rate",
   "type": "timeseries",
   "description": "Updates from v2 pollers sent to pubsub. Abnormal spikes could be from spam or lack of duplicate suppression in the proxy.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "sum by (payload_type) (rate(sliding_sync_poller_num_payloads{}[$window_size]))",
     "legendFormat": "{{payload_type}}"
    }
   ]
  },
  {
   "title": "Poller processing time quantiles",
   "type": "timeseries",
   "description": "Excludes time waiting for v2 sync requests. Excludes initial polls.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(sliding_sync_poller_process_duration_secs_bucket{initial=\"0\"}[$window_size])))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(sliding_sync_poller_process_duration_secs_bucket{initial=\"0\"}[$window_size])))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(sliding_sync_poller_process_duration_secs_bucket{initial=\"0\"}[$window_size])))",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(sliding_sync_poller_process_duration_secs_bucket{initial=\"0\"}[$window_size])))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(sliding_sync_poller_process_duration_secs_bucket{initial=\"0\"}[$window_size])))",
     "legendFormat": "25%"
    },
    {
     "expr": "sum(rate(sliding_sync_poller_process_duration_secs_count{initial=\"0\"}[$window_size]))",
     "legendFormat": "Poll rate"
    }
   ]
  }
 ]
}